### ISSUE TITLE
[client] [Landing] - Landing Part-6 디자인 및 애니메이션 추가

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#117]
### ISSUE
- Group: `client`
- Type:  `feature`
- Detail: Landing페이지에 들어갈 svg를 애니메이션으로 구현한다.

### TODO
1. [x] 화면에 들어갈 svg를 좌표를 찍어가며 만든다.
2. [x] DOM을 활용하여 svg에 접근한다.
3. [x] 현재 스크롤 위치와 svg 길이를 이용해서 스크롤을 내릴때마다 svg 태그가 나오도록 구현한다.
