### ISSUE TITLE
[client] [Landing] - Landing Part-6 문구 추가 및 마무리 점검

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#124]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: Landing Part-6 부분 문구 추가 및 마무리 점검을 한다.

### TODO
1. [ ] 적절한 위치에 문구를 넣어준다.
2. [ ] 스크롤을 내릴 시 문구에 명암 효과를 넣어준다.
3. [ ] 스크롤을 내릴 시 이벤트에 이상이 없는지 마무리 확인을 한다.
