### ISSUE TITLE
[client] [Bare Minimum] - 유효성 검사 유틸 구현

### ISSUE THREAD

**Issue by Woogie-94** [codestates/Reciper-client#160]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 이메일이나 Project에 사용되는 name, url 등 유효성 검사를 위한 유틸 제작

### TODO
1. [ ] EmailValid 유틸 제작
2. [ ] ProjectNameValid 유틸 제작
3. [ ] ProjectURLValid 유틸 제작
