### ISSUE TITLE
[client] [Common Components] - WorkSpaceFrame list item 삭제 버튼 클릭 시 경고 모달 창 구현 

### ISSUE THREAD

**Issue by Woogie-94** [codestates/Reciper-client#173]
### ISSUE
- Group: `client`
- Type: `bug`, `feature`, `delete`
- Detail: 삭제 시 안에 있는 내용이 전부 사라진다는걸 인지 시키기 위한 경고 창을 모달 형태로 구현

### TODO
1. [x] 삭제 버튼 클릭 시 경고 창 띄우기
2. [x] 경고 창의 삭제 버튼 클릭 시 item 삭제
3. [x] 경고 창의 취소 버튼 클릭 시 모달 창 닫힘
