### ISSUE TITLE
[client] [Workspace - Chat] - 채팅방 나누기 기능 구현

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#196]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 채팅방을 나누어서 socket으로 통신한다.

### TODO
1. [x] 쿼리를 구분해서 서버와 socket 통신을 한다.
2. [x] room이 바뀔 때 마다 감지해서 해당 room을 서버에 전달해주고 데이터를 받는다.
3. [x] room이 바뀌면 해당하는 room에 대한 채팅 기록만 뿌려준다.
