### ISSUE TITLE
[client] [Common Components] - Input, Button, Select 컴포넌트 기능 추가 & 수정 사항

### ISSUE THREAD

**Issue by Woogie-94** [codestates/Reciper-client#21]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: Input과 Button을 실제 사용하면서 수정해야 하거나 추가해야 하는 기능들을 구현합니다.

### TODO
1. [x] Input과 Button에게 마진을 유동적으로 넣을 수 있도록 기능을 추가
2. [x] Input에 onKeyPress 이벤트 함수 추가
3. [x] Select OptionContainer에 백그라운드 컬러 추가
4. [x] Select에서 마우스가 벗어나면 Option이 닫히게 변경 
4. [x] 각 컴포넌트에 사용법 주석 달기
