### ISSUE TITLE
[client] [Kanban] - Drag Block 기능 구현

### ISSUE THREAD

**Issue by Woogie-94** [codestates/Reciper-client#224]
### ISSUE
- Group: `client`
- Type: `bug`, `feature`, `delete`
- Detail: 유저가 아이템을 집을 때 다른 유저가 해당 아이템을 드래그하지 못하도록 블럭시킨다.

### TODO
1. [x] 다른 사람이 집은 아이템 구분하기
2. [x] 다른 사람이 집은 아이템 css
3. [x] 다른 사람이 집을 수 없도록 드래그 이벤트 끊어주기
