### ISSUE TITLE
[client] [Workspace - Chat] - Chat Item 프로필 이미지 클릭 시 프로필 보기 기능 구현

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#226]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: Chat Item에서 채팅을 남긴 사람의 프로필 사진을 누르면 그 사람의 프로필을 볼 수가 있다.

### TODO
1. [x] 채팅에서 프로필 이미지를 누르면 프로필을 볼 수 있는 모달창을 띄운다.
2. [x] 본인이 자신의 채팅 프로필 이미지를 누르면 레시피 보기, 프로필 편집 기능이 나오도록 한다.
3. [x] 다른 사람 채팅 프로필 이미지를 누르면 전체 프로필을 볼 수 있는 기능을 구현한다.
