### ISSUE TITLE
[client] [Workspace - Chat] - Chat Image Upload 기능 구현

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#236]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 채팅에서 이미지 업로드 기능을 구현한다.

### TODO
1. [x] 먼저 서버에 이미지 요청 업로드 요청을 하고 응답을 받는다.
2. [x] 업로드 응답으로 받아 온 값을 socket 양방향 통신으로 다시 서버에게 요청한다.
3. [x] socket을 통해 받은 값을 화면에 나타내어 준다.
