### ISSUE TITLE
[client] [Workspace - Chat] - drag & drop으로 채팅 이미지 업로드 기능 구현

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#244]
### ISSUE
- Group: `client`
- Type:  `feature`
- Detail:  drag & drop으로 채팅 이미지 업로드를 할 수 있도록 기능을 구현한다.

### TODO
1. [x] Chat zone에 drag & drop 이벤트를 걸어 놓는다.
2. [x] drop이 되었을 때 채팅 이미지 업로드를 서버에 요청한다.
3. [x] 서버에서 받아 온 이미지 값을 다시 socket으로 서버랑 통신한다.
