### ISSUE TITLE
[client] [Workspace - Chat] - 채팅방 리버스 인피니티 스크롤 기능 구현

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#255]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 채팅방 리버스 인피니티 스크롤 기능 구현

### TODO
1. [x] 채팅방을 들어왔을 때 처음에는 채팅 기록의 30개만 불러온다.
2. [x] 그 후 채팅방에서 위로 스크롤을 올렸을 경우 채팅 기록의 데이터를 30개씩 불러온다.
3. [x] 채팅 데이터 30개를 불러오고 스크롤 위치는 맨 밑, 맨 위가 아닌 중간 위치로 가게한다.
