### ISSUE TITLE
[client] [Workspace - Chat] - Chat Profile 모달창 CSS 수정 및 위치 수정

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#262]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 채팅에서 프로필 이미지를 클릭했을 때 나오는 모달창 CSS 수정 및 모달창 위치 수정

### TODO
1. [x] 모달창 버튼을 수정한다. DM기능을 취소했으므로, 다른 유저의 프로필 이미지를 클릭했을 때는 전체 프로필 보는 버튼만 생성한다.
2. [x] 프로필 이미지를 클릭한 상태에서 다른 유저의 프로필 이미지를 클릭하면 모달창은 하나씩만 띄우게 한다.
3. [x] 프로필 이미지 즉, 채팅 기록이 밑 쪽에 있을 경우는 채팅창 안에 들어 올 수 있도록 위치에 맞게 모달창을 띄워준다.
