### ISSUE TITLE
[client] [Bare Minimum] - 상태관리를 위한 redux store 생성

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#31]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: redux 파일에서 store를 생성한다.

### TODO
1. [x] store 파일에 createslice 함수 연결
2. [x] loger 및 미들웨어 연결
3. [x] index 파일에서 store 연결
