### ISSUE TITLE
[client] [Landing] - Landing Page Part 8 CSS 수정 및 마무리

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#322]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: Landing Page Part 8 디자인을 하고 CSS 수정을 한다.

### TODO
1. [x] 랜딩 페이지 마지막 부분을 어떻게 하면 좋을지 구상한다.
2. [x] 구상을 하고 CSS를 적용한다.
3. [x] 랜딩페이지 마무리 작업을 한다.
