### ISSUE TITLE
[client] [Common Components] - StackSearch 컴포넌트 제작

### ISSUE THREAD

**Issue by Woogie-94** [codestates/Reciper-client#33]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 사용자가 Stak을 고를 수 있도록 목록을 불러 와 선택할 수 있게 제작합니다. 목록은 데이터베이스에 존재하므로 서버와 연결하여 불러와야 합니다.

### TODO
1. [x] StackSearch 디자인
2. [x] 서버에서 Stack 목록 불러오기
3. [x] 불러온 Stack을 담아 화면에 출력
4. [x] Stack을 고르면 StackSearch 컴포넌트를 사용한 곳으로 상태를 전달
