### ISSUE TITLE
[client] [Profile] - Profile page CSS 수정 및 코드 리팩토링

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#344]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: Profile page CSS 수정 및 코드 리팩토링

### TODO
1. [x] 프로필 페이지의 CSS 구조등 크기를 변경한다.
2. [x] CSS 코드를 가다듬는다.
3. [x] 컴포넌트의 코드들을 리팩토링한다.
