### ISSUE TITLE
[client] [Profile] - 프로필 이미지 변경 기능 구현

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#37]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 유저의 프로필을 사진으로 변경할 수 있는 기능을 구현한다.

### TODO
1. [x] 프로필이 없으면 기본 색상을 부여한다.
2. [x] 프로필을 변경하려고 사진에 마우스를 올리면 mouse hover 기능을 걸어준다.
3. [x] 이미지로 변경할 수 있도록 기능을 구현한다.
4. [x] 이미지를 서버에 요청하고 이미지를 화면에 나타낸다.
