### ISSUE TITLE
[client] [Chat] - 채팅 CSS 수정 및 점검

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#376]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 배포 전 워크스페이스 채팅 부분을 점검하고 피드백을 받은 CSS 부분을 수정한다.

### TODO
1. [x] 채팅 `hover`시 배경화면이 너무 짙어서 톤 다운을 위해 CSS를 수정한다.
2. [x] 채팅 input의 `padding`을 수정한다. 
3. [x] 배포전에 채팅시 생기는 오류가 있는지 점검 한다.
