### ISSUE TITLE
[client] [Profile] - 프로필 한줄 소개 글자 제한 수 변경 및 CSS 수정

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#380]
### ISSUE
- Group: `client`
- Type:`feature`
- Detail: 프로필 한줄 소개란에 글자 제한 수를 15자에서 50자까지 늘린다.

### TODO
1. [x] 프로필 유효성 검사 함수 수정
2. [x] 프로필에 한줄 소개 표시부분에 글자 수 넘쳐도 CSS 구조 망가지지 않게 수정
3. [x] 채팅에서 유저 프로필 모달창 CSS 수정
