### ISSUE TITLE
[client] [Profile] - Profile 페이지 여러 이슈 해결

### ISSUE THREAD

**Issue by Woogie-94** [codestates/Reciper-client#408]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 폰트가 제대로 적용되지 않은 부분들과 height을 vw로 잡아 화면의 크기에 따라 너무 달라지는 문제를 해결한다.

### TODO
1. [x] 기술 스택 조건 초기화 폰트 적용
2. [x] Edit 페이지 개발, 완성 레시피 폰트 적용
3. [x] height에 vw 단위를 쓴 부분들 고치기
