### ISSUE TITLE
[client] [Workspace - Chat] - 성능개선을 위해 useState를 Redux로 리팩토링

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#409]
### ISSUE
- Group: `client`
- Type:  `feature`
- Detail: 서버에서 받아오는 데이터를 setState로 관리하고 있었는데 props로 넘겨주는 상태가 많아서 Redux로 상태관리 하기로 변경한다.

### TODO
1. [x] chat reducer 만들기
2. [x] chat 데이터를 담고 있던 `useState`를 지우고 서버에서 받아오는 데이터를 `store`에 저장한다.
3. [x] useSelecotor를 통해 `store`에서 chat 데이터를 가져온다.
