### ISSUE TITLE
[client] [Workspace - Chat] - 채팅 삭제 및 수정 기능 성능개선을 위해 전면 Redux로 리팩토링

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#416]
### ISSUE
- Group: `client`
- Type:  `feature`
- Detail: 채팅 수정 및 삭제를 하기 위해 채팅 데이터를 담고 있던 state를 props로 통해 채팅 컴포넌트까지 내려주고 있었다. 강제 렌더링을 막기 위해 `redux`로 리팩토링 한다.

### TODO
1. [x] 채팅 데이터를 `redux`로 관리한다.
2. [x] reducer에서 채팅 수정 및 삭제 액션을 추가한다.
3. [x] 실시간으로 잘 적용이 되는지 테스트한다.
