### ISSUE TITLE
[client] [Workspace - Chat] - 채팅 Redux로 리팩토링 후 에러 점검

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#421]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 채팅 기능을 전면 Redux로 리팩토링하면서 생기는 에러들을 해결한다.

### TODO
1. [x] Redux로 완전히 리팩토링을 끝낸다.
2. [x] 기능을 테스트해보면서 에러가 있는지 찾아낸다.
3. [x] 에러가 있을 시 해결한다.
