### ISSUE TITLE
[client] [Common Components] - StackSearch 컴포넌트 여러가지 이슈 해결

### ISSUE THREAD

**Issue by Woogie-94** [codestates/Reciper-client#439]
### ISSUE
- Group: `client`
- Type:  `feature`
- Detail: StackSearch 컴포넌트의 자잘한 이슈들을 해결하고 필터 기능을 정규식으로 바꾼다.

### TODO
1. [x] 검색 결과가 없을 때 안내 메시지 출력
2. [x] 작성 후 포커스를 아웃 인 하면 다시 전체 리스트가 출력되는 문제 해결
3. [x] 필터 기능을 정규식으로 교체
