### ISSUE TITLE
[client] [Recruit] - Infinite Scroll 성능 개선 및 리팩토링

### ISSUE THREAD

**Issue by Woogie-94** [codestates/Reciper-client#453]
### ISSUE
- Group: `client`
- Type: `bug`
- Detail: IntersectionObserver를 이용한 Infinite Scroll 기능에 개선할 점이 생겼다. 기존에 감시하던 ObserveBlock 대신 RecruitCard의 마지막 요소를 감시한다. Observer의 타겟을 바꿈으로서 Infinite Scroll의 안정성이 높아진다. 안정성이 높아지기 전에 작성한 안전 장치로 작성한 코드들을 지워야 한다.

그리고 Recruit 데이터를 Redux로 관리하도록 수정한다. thunk를 함께 이용해 요청 진행 상태를 기존의 로딩 상태 대신 사용한다.

### TODO
1. [x] IntersectionObserver을 이용한 Infinite Scroll 안정성 확보
2. [x] Recruit 데이터를 Redux, thunk를 이용해 리팩토링
3. [x] 쓸모 없는 코드 제거
