### ISSUE TITLE
[client] [Profile] - 스택 추가 input태그를 StackSearch 컴포넌트로 변경

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#55]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 스택을 추가할 때 검색을 통하여 추가할 수 있도록 구현한다.

### TODO
1. [x] input 태그를 지우고 StackSearch 컴포넌트를 가져온다.
2. [x] css를 설정하여 태그가 페이지와 크기가 맞게 설정해준다.
3. [x] 검색을 하면 스택들이 하나씩 쌓이도록 해준다.
