### ISSUE TITLE
[client] [Common Component] - 유저 프로필 이미지 컴포넌트 구현

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#81]
### ISSUE
- Group: `client`
- Type:  `feature`
- Detail: 모든 페이지에서 사용되는 유저 프로필 이미지를 컴포넌트로 만든다.

### TODO
1. [x] 유저의 로그인 상태에 따라 보여지는 유저 프로필 이미지를 컴포넌트로 만든다.
2. [x] 유저가 프로필 이미지를 변경했으면 이미지를 보여주고, 설정하지 않았으면 기본 프로필을 보여준다.
3. [x] 크기를 마음대로 조정할 수 있게 만든다.
