### ISSUE TITLE
[client] [Landing] - 랜딩 페이지 기획 및 CSS 구조

### ISSUE THREAD

**Issue by useonglee** [codestates/Reciper-client#94]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 랜딩 페이지를 기획하고 CSS 틀을 잡는다.

### TODO
1. [x] 랜딩페이지를 어떻게 구성할지 생각한다.
2. [x] 랜딩페이지에 들어갈 문구 및 애니메이션을 생각한다.
3. [x] CSS로 랜딩페이지의 구조를 잡는다.
